POST http://localhost:8080/doctor/createDoctor
Content-Type: application/json

{
"name": {
  "firstName": "Ricardo",
  "lastName": "Pita"
},
  "age": 25,
  "email": "",
  "gender": "MALE",
  "dateOfBirth": "1992-01-01",
  "department": "Cardiology"
}

###
GET http://localhost:8080/doctor
Content-Type: application/json

###
GET http://localhost:8080/doctor/availableHours/1/13-04-2024
Content-Type: application/json

###
POST http://localhost:8080/doctor/createDoctor
Content-Type: application/json

{
  "name": {
    "firstName": "Miguel",
    "lastName": "Silva"
  },
  "age": 25,
  "email": "brainfiddler@brains.com",
  "gender": "MALE",
  "dateOfBirth": "1998-01-01",
  "department": "Neurology"
}

###
GET http://localhost:8080/doctor/availableHours/3/20-04-2023
Content-Type: application/json

####
GET http://localhost:8080/doctor/printSchedule/1/17-04-2024
