###
GET localhost:8080/medicalinformation/getMedicalInformation
###
POST localhost:8080/medicalinformation/createMedicalInformation
Content-Type: application/json

{
  "patientId": 4,
  "data": "03/06/2024",
  "sintoms": "dor de cabeça",
  "diagnostic": "está com dores de cabeça",
  "medication": "beber muita água",
  "notes": "bateu com a cabeça, deve beber água."
}
###
PUT localhost:8080/medicalinformation/25/updateMedicalInformation
Content-Type: application/json

{
  "patientId": 4,
  "data": "03/06/2024",
  "sintoms": "diarreia severa moded",
  "diagnostic": "comeu coisas más",
  "medication": "beber muita água e tomar algo",
  "notes": "comeu algo que não devia, deve beber água."
}
###
PUT localhost:8080/medicalinformation/4/updateMedicalInformation
Content-Type: application/json

{
  "patientId": 4,
  "data": "03/06/2024",
  "sintoms": "diarreia",
  "diagnostic": "comeu coisas más",
  "medication": "beber muita água",
  "notes": "comeu algo que não devia, deve beber água."
}
###
DELETE localhost:8080/medicalinformation/22/deleteMedicalInformation
###
GET localhost:8080/medicalinformation/4/getMedicalInformation
###
GET localhost:8080/medicalinformation/4/genPdf
###