GET http://127.0.0.1:8080/patients
Content-Type: application/json

###
POST http://127.0.0.1:8080/patients/createPatient
Content-Type: application/json

{
"name": {
    "firstName": "Macaco",
    "lastName": "Banana"
    },
  "age": 23,
  "email": "macaco@gmail.com",
  "gender": "MALE",
  "dateOfBirth": "1992-01-01",
  "nationalHealthNumber": 123456790
}

###
POST http://127.0.0.1:8080/patients/createPatient
Content-Type: application/json

{
  "name": {
    "firstName": "Alice",
    "lastName": "Smith"
  },
  "age": 30,
  "email": "alice.smith@example.com",
  "gender": "FEMALE",
  "dateOfBirth": "1994-05-15",
  "nationalHealthNumber": 987654321
}

###
POST http://127.0.0.1:8080/patients/createPatient
Content-Type: application/json

{
  "name": {
    "firstName": "Bob",
    "lastName": "Johnson"
  },
  "age": 45,
  "email": "bob.johnson@example.com",
  "gender": "MALE",
  "dateOfBirth": "1979-09-20",
  "nationalHealthNumber": 246810975
}
###
//Should fail with conflict
###
POST http://127.0.0.1:8080/patients/createPatient
Content-Type: application/json

{
  "name": {
    "firstName": "Bob",
    "lastName": "Johnson"
  },
  "age": 45,
  "email": "bob.johnson@example.com",
  "gender": "MALE",
  "dateOfBirth": "1979-09-20",
  "nationalHealthNumber": 246810975
}

###
POST http://127.0.0.1:8080/patients/createPatient
Content-Type: application/json

{
  "name": {
    "firstName": "Emma",
    "lastName": "Davis"
  },
  "age": 27,
  "email": "emma.davis@example.com",
  "gender": "FEMALE",
  "dateOfBirth": "1997-02-10",
  "nationalHealthNumber": 135792468
}

###
POST http://127.0.0.1:8080/patients/createPatient
Content-Type: application/json

{
  "name": {
    "firstName": "John",
    "lastName": "Brown"
  },
  "age": 33,
  "email": "john.brown@example.com",
  "gender": "MALE",
  "dateOfBirth": "1991-11-03",
  "nationalHealthNumber": 112233445
}

###
POST http://127.0.0.1:8080/patients/createPatient
Content-Type: application/json

{
  "name": {
    "firstName": "Olivia",
    "lastName": "Martinez"
  },
  "age": 28,
  "email": "olivia.martinez@example.com",
  "gender": "FEMALE",
  "dateOfBirth": "1996-07-25",
  "nationalHealthNumber": 987123654
}

###
POST http://127.0.0.1:8080/patients/createPatient
Content-Type: application/json

{
  "name": {
    "firstName": "Michael",
    "lastName": "Wilson"
  },
  "age": 40,
  "email": "michael.wilson@example.com",
  "gender": "MALE",
  "dateOfBirth": "1984-03-12",
  "nationalHealthNumber": 456789123
}

###
POST http://127.0.0.1:8080/patients/createPatient
Content-Type: application/json

{
  "name": {
    "firstName": "Sophia",
    "lastName": "Taylor"
  },
  "age": 35,
  "email": "sophia.taylor@example.com",
  "gender": "FEMALE",
  "dateOfBirth": "1989-08-18",
  "nationalHealthNumber": 369258147
}

###
POST http://127.0.0.1:8080/patients/createPatient
Content-Type: application/json

{
  "name": {
    "firstName": "David",
    "lastName": "Anderson"
  },
  "age": 50,
  "email": "david.anderson@example.com",
  "gender": "MALE",
  "dateOfBirth": "1974-12-05",
  "nationalHealthNumber": 987654123
}

###
POST http://127.0.0.1:8080/patients/createPatient
Content-Type: application/json

{
  "name": {
    "firstName": "Emily",
    "lastName": "Thomas"
  },
  "age": 31,
  "email": "emily.thomas@example.com",
  "gender": "FEMALE",
  "dateOfBirth": "1993-06-28",
  "nationalHealthNumber": 654321987
}

###
POST http://127.0.0.1:8080/patients/createPatient
Content-Type: application/json

{
  "name": {
    "firstName": "James",
    "lastName": "Jackson"
  },
  "age": 42,
  "email": "james.jackson@example.com",
  "gender": "MALE",
  "dateOfBirth": "1982-10-07",
  "nationalHealthNumber": 147258369
}
###
//Update info tests
###
POST http://127.0.0.1:8080/patients/1/updateInfo
Content-Type: application/json

  {
    "name": {
      "firstName": "Fernando",
      "lastName": "Matos"
    },
    "age": 54,
    "email": "fernando.matos42@gmail.com",
    "gender": "MALE",
    "nationalHealthNumber": 123452135
  }
###
//Update Bob
###
POST http://127.0.0.1:8080/patients/5/updateInfo
Content-Type: application/json

{
  "name": {
    "firstName": "Mario",
    "lastName": "Luigi"
  },
  "age": 35,
  "email": "luigi.mario@example.com",
  "gender": "MALE",
  "nationalHealthNumber": 987654321
}
###
POST http://127.0.0.1:8080/patients/5/updateInfo
Content-Type: application/json

{
"name": {
"firstName": "John",
"lastName": "Wick"
},
"age": 45,
"email": "bullets4everyone@edgy.com",
"gender": "MALE",
"nationalHealthNumber": 156534687
}
###
//Delete patient with id
###
DELETE http://127.0.0.1:8080/patients/delete/14


